- name: Set a hostname
  ansible.builtin.hostname:
    name: mongodb
    use: systemd

- name: Setting up the MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/
    follow: yes

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
        state: latest

- name: Updating listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enabling MongoDB Server
  ansible.builtin.service:
    name: mongod
    enabled: yes

- name: Restarting MongoDB Server
  ansible.builtin.service:
    name: mongod
    state: restarted