- name: Install maven
  yum:
    name: maven
    state: installed

- name: load the common role
  include_role:
    name: common
    tasks_from: app_presetup

- name: install dependencies
  shell: mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: "{{app_path}}"

-  name: load the common role
   include_role:
      name: common
      tasks_from: systemd_setup

- name: load the common role
  include_role:
    name: common
    tasks_from: mysql-client

