- name: Load NodeJS yml file
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
    

















# source common.sh
# component=catalogue

# nodejs
# mongodb-client-setup





