- name: Load NodeJS yml file
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

# - name: mongodb-client-setup
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: mongodb-client-setup
    

















# source common.sh
# component=catalogue

# nodejs
# mongodb-client-setup





