- name: configuring nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name:  install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Load the app_presetup yml file
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Install dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: "{{app_path}}"

- name: Load the systemd_setup yml file
  ansible.builtin.import_tasks:
    name: common
    file: systemd_setup.yml











