- name: configuring nodejs repos
  shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing the nodejs 18
  yum:
    name: nodejs
    state: installed

- name: app_presetup
  include_tasks:
    file: app_presetup.yml

- name: Installing dependencies
  shell: npm install chdir="{{app_path}}"

- name: systemd_setup
  include_tasks:
    file: systemd_setup.yml








