- name: setting up "{{component}}" service
  copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/

- name: Enable Reload and Restart "{{component}}" service
  service:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

