- name: Creating Service File
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/
    follow: yes

- name: Enabling {{component}} service
  ansible.builtin.service:
    name: "{{component}}"
    enabled: yes
    daemon-reload: yes

- name: Restarting {{component}} Service
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted